hdb_inicio:
    pattern:  /
    defaults: { _controller: HDBwebBundle:Default:index }

hdb_servicios:
    pattern: /servicios/
    defaults: { _controller: HDBwebBundle:Servicios:servicios }
    
hdb_cazaycampo:
    pattern: /cazaycampo/
    defaults: { _controller: HDBwebBundle:CazaYCampo:cazaYCampo }