<?php

namespace HDB\webBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactoRapidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactoRapidoRepository extends EntityRepository
{
}
